### ISSUE TITLE
ERROR: Message 'includes' not understood.

### ISSUE THREAD

**Issue by buscon** [DarienBrito/NLC#1]
I successfully installed the NLC library but when i try to run the first example, at the moment of creating an NLC element:
a = NLC_Element(x, \masks, \sine); 
I get the following error. 
I am running it on OSX 10.11 and tried both SC 3.7.2 and 3.8 with the same output.

ERROR: Message 'includes' not understood.
RECEIVER:
   nil
ARGS:
   Symbol 'out'
PATH: /Users/marcello/Music/Supercollider/Projects/TouchAudioSoundcard/data_selection_trigger.scd
CALL STACK:
	DoesNotUnderstandError:reportError   0x11c6175c8
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x11c5a0af8
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x11c597df8
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x11c58d9e8
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x11bb49a68
		arg this = nil
		arg selector = 'includes'
		arg args = [*1]
	NLC_BaseElement:initData   0x11c0f3b38
		arg this = <instance of NLC_MasksElement>
		arg synth = <instance of SynthDef>
		var innerLabels = [*1]
		var innerParameters = [*1]
		var argumentNames = nil
		var synthParameters = nil
		var template = <instance of SynthDef>
		var removalIndex = nil
	NLC_BaseElement:invokeData   0x11c5a2658
		arg this = <instance of NLC_MasksElement>
		arg synth = <instance of SynthDef>
		arg patternType = 'Pbind'
	NLC_MetaElement:init   0x11c0f3c68
		arg this = <instance of NLC_MasksElement>
		arg synth_ = <instance of SynthDef>
		arg name_ = 'sine'
		arg patternType_ = 'Pbind'
	NLC_Element:init   0x11c55daa8
		arg this = <instance of NLC_Element>
		arg patternType_ = 'Pbind'
	< closed FunctionDef >  (no arguments or variables)
	Interpreter:interpretPrintCmdLine   0x11c0f45e8
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "a = NLC_Element(x, \masks, \..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x117ef5b48
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'includes' not understood.
RECEIVER: nil

**Comment by DarienBrito** [comment]
Ok, it seems something is wrong with the initialization of the NLC_BaseElement class from the NLC_Element class.

Please try the following:

1) Create a new file in SuperCollider and save it in Desktop
2) In this new file, just type:

`a = NLC_BaseElement();
`

Are you able to create this object with no errors?

**Comment by buscon** [comment]
Hi Darine,

thanks for your answer.

yes, i can create the BaseElement you suggested without errors.

**Comment by DarienBrito** [comment]
Hello there!

Ok, second step is to see if you can add a synth with no errors. Create the following synth first: 

`(
x =  SynthDef(\test, {|freq = 120, amp = 0.5, envDur = 0.1, out|
  var sig = SinOsc.ar(freq) * amp;
  sig = EnvGen.kr(Env.perc(releaseTime:envDur), doneAction: 2) * sig;
  Out.ar(out, sig);
}).add;
)
`

and then initialize and test a meta-element with the following lines:

`
a = NLC_MetaElement(x, \test);
a.params;
`

you then should be able to see this in the console:

`Current Parameters: 

	- [ freq, 120 ]
	- [ amp, 0.5 ]
	- [ envDur, 0.1 ]
	- [ dur, 1 ]

-> a NLC_MetaElement`

**Comment by buscon** [comment]
hi and thanks!

i still get the same error when i initialize the MetaElement:

ERROR: Message 'includes' not understood.
RECEIVER:
   nil
ARGS:
   Symbol 'out'
PATH: /Users/marcello/Downloads/test.scd
CALL STACK:
	DoesNotUnderstandError:reportError   0x10c94cba8
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x10c901508
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x10c907f98
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x10c903348
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x10c90dbf8
		arg this = nil
		arg selector = 'includes'
		arg args = [*1]
	NLC_BaseElement:initData   0x111e6b828
		arg this = <instance of NLC_MetaElement>
		arg synth = <instance of SynthDef>
		var innerLabels = [*1]
		var innerParameters = [*1]
		var argumentNames = nil
		var synthParameters = nil
		var template = <instance of SynthDef>
		var removalIndex = nil
	NLC_BaseElement:invokeData   0x10c901198
		arg this = <instance of NLC_MetaElement>
		arg synth = <instance of SynthDef>
		arg patternType = nil
	NLC_MetaElement:init   0x111e6c078
		arg this = <instance of NLC_MetaElement>
		arg synth_ = <instance of SynthDef>
		arg name_ = 'test'
		arg patternType_ = nil
	< closed FunctionDef >  (no arguments or variables)
	Interpreter:interpretPrintCmdLine   0x111e6dff8
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "a = NLC_MetaElement(x, \test..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x10c847168
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'includes' not understood.
RECEIVER: nil

**Comment by DarienBrito** [comment]
Alright, it seems that the message 'includes' itself is the real issue. Can you try:

`[\this, \is, \a, \test].includes(\test); `

Does it return true, or does that also give you an error?

**Comment by buscon** [comment]
when I run that include command i get a true, so that works.

**Comment by DarienBrito** [comment]
Mmm, strange. I will have to look further into it. 
I'm assuming you installed all the dependencies listed in the README file of course?

I cannot replicate this error Running on OSX 10.11, with SC 10.8 or 10.7, I will try later on another machine and will come back to you.

**Comment by buscon** [comment]
On 14/12/16 17:01, Darien wrote:
> Mmm, strange. I will have to look further into it.
> I'm assuming you installed all the dependencies listed in the README
> file of course?

yes, all installed correctly.

> I cannot replicate this error Running on OSX 10.11, with SC 10.8 or
> 10.7, I will try later on another machine and will come back to you.

ok, thanks a lot!

**Comment by buscon** [comment]
Dear Darien,

I looked a bit into the issue.
Apparently the list of arguments of the synth is empty

- in your class you look for a list of arguments of the synthdef with:
argumentNames = (template.func.argNames).collect{|a| a};

If i execute this directly on my synthdef i get a nil output:
(x = SynthDef(\test, {|freq = 120, amp = 0.5, envDur = 0.1, out = 0| var
sig = SinOsc.ar(freq) * amp; sig =
EnvGen.kr(Env.perc(releaseTime:envDur), doneAction: 2) * sig;
Out.ar(out, sig); }).add; )
x.func.argNames
-> nil

- Instead i think it should be:
argumentNames = (template.desc.controlNames).collect{|a| a};

(x = SynthDef(\test, {|freq = 120, amp = 0.5, envDur = 0.1, out = 0| var
sig = SinOsc.ar(freq) * amp; sig =
EnvGen.kr(Env.perc(releaseTime:envDur), doneAction: 2) * sig;
Out.ar(out, sig); }).add; )
x.desc.controlNames.includes(\out)

This way it works for me.


If it makes sense for you, i can do a pull request. what do you think?

best regards,
Marcello

**Comment by DarienBrito** [comment]
Hello Marcello!

I didn't have time to look at the issue yet, glad you had a look into it!
It is a little bit odd that when you execute:

`template.func.argNames`

it returns nil. I get instead a SymbolArray with the right argument names...mmm...however, Is great you spotted this because what I was doing:

`argumentNames = (template.func.argNames).collect{|a| a};`

Is a workaround for the fact that SymbolArrays behave weirdly when you concatenate them with other stuff, hence I had to convert it first to a standard Array. Using your solution we can get rid of the collect and simply say:

`argumentNames = template.desc.controlNames`

That is the cleanest version I think, so yes, please, send the pull request! :)

Best,
Darien

**Comment by buscon** [comment]
Ok, done!

now i'm wondering, which version is supposed to be the most correct one
to collect the arguments of a synthdef? synth.func or synth.desc ?

best,
Marcello

**Comment by DarienBrito** [comment]
Great! Merge done. According to the Help files a desc: 

> contains a description of a SynthDef, including its name, control names and default values. Information is also stored on its outputs and inputs and whether it has a gate control

 which sounds like the appropriate thing to use in this case. The collect I was doing was a kinda hacky way of preventing errors, so I think your suggestion is an improvement ;)

Thanks for your contribution!
Darien

**Comment by buscon** [comment]
Hey Darien,

On 16/12/16 17:44, Darien wrote:
> Great! Merged done. According to the Help files a desc:
> 
> contains a description of a SynthDef, including its name, control names
> and default values. Information is also stored on its outputs and inputs
> and whether it has a gate control
> 
> which sounds like the appropriate thing to usein this case. The collect
> I was doing was a kinda hacky way of preventing errors, so I think your
> suggestion is an improvement ;)

ok, thanks for your answer, now it's all more clear!

> Thanks for your contribution!

you're welcome, thanks for the Quark, i will explore it in the next days ;)

best,
Marcello
