### ISSUE TITLE
Autorandom doesn't turn off 

### ISSUE THREAD

**Issue by tatecarson** [DarienBrito/NLC#3]
When autorandom is on it doesn't turn off. Each of the other auto buttons seem to work with both states. Also, what is the viz button supposed to do? It doesn't seem to do anything.

**Comment by DarienBrito** [comment]
Hi Tate,

Thanks for spotting this. The function for "off button" in the GUI for autoRandom in the type Masks was calling the wrong method. See the log for the file change.

Please confirm it works now for you.

Best,
Darien

**Comment by DarienBrito** [comment]
Oh and the viz button will show you the changes in the GUI in real time (when morphing). If de-selected, you will not see changes in the GUI anymore.
